# -*- coding: utf-8 -*-
"""Customer-Data-Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZSFvtjS26hiNhK-HlUELaOVWZX__p29
"""

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age': [25, np.nan, 35, np.nan, np.nan, 40],
    'city': ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

df['age'] = df['age'].fillna(df['age'].median())
df['city'] = df['city'].fillna(df['city'].mode()[0])

df = df.drop_duplicates().reset_index(drop=True)

print("--- Cleaned Dataframe ---")
print(df)

from sklearn.preprocessing import LabelEncoder

df = pd.get_dummies(df, columns=['city'], prefix='city')

le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

print("\n--- Encoded Dataframe ---")
print(df)

from sklearn.preprocessing import MinMaxScaler, StandardScaler

features = ['age', 'annual_income']

scaler_minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[features] = scaler_minmax.fit_transform(df[features])

scaler_std = StandardScaler()
df_std = df.copy()
df_std[features] = scaler_std.fit_transform(df[features])

print("\n--- Min-Max Scaled Results ---")
print(df_minmax[features])

print("\n--- Standardised Results ---")
print(df_std[features])